### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by askaper** [synapsestudios/google-places-field#4]
After cloning the repo and doing an npm install I receive the following output:

`$ npm i
npm WARN prepublish-on-install As of npm@5, prepublish scripts will run only for npm publish.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for npm install.)
npm WARN prepublish-on-install See the deprecation note in npm help scripts for more information.

> @synapsestudios/google-places-field@0.2.2 prepublish C:\Users\Andrew\webstuff\google-places-field
> npm run lint && npm test && npm run build

> @synapsestudios/google-places-field@0.2.2 lint C:\Users\Andrew\webstuff\google-places-field
> eslint src

C:\Users\Andrew\webstuff\google-places-field\src\index.js
  1:53  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  2:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  3:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 3 problems (3 errors, 0 warnings)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @synapsestudios/google-places-field@0.2.2 lint: eslint src
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @synapsestudios/google-places-field@0.2.2 lint script 'eslint src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @synapsestudios/google-places-field package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @synapsestudios/google-places-field
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @synapsestudios/google-places-field
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andrew\webstuff\google-places-field\npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @synapsestudios/google-places-field@0.2.2 requires a peer of react@^15.4.0 but none was installed.
npm WARN react-addons-shallow-compare@15.4.2 requires a peer of react@^15.4.2 but none was installed.
npm WARN react-geosuggest@2.1.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @synapsestudios/google-places-field@0.2.2 prepublish: npm run lint && npm test && npm run build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @synapsestudios/google-places-field@0.2.2 prepublish script 'npm run lint && npm test && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @synapsestudios/google-places-field package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm test && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @synapsestudios/google-places-field
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @synapsestudios/google-places-field
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andrew\webstuff\google-places-field\npm-debug.log
`

**Comment by chrisheninger** [comment]
Talked to Andrew separately over Slack, the above issue should be fixed with my script/lint/etc. updates in 0.3.0.
